In [1]:
import numpy as np

In [2]:
# preds_1 = 1 epoch
pred_coords_1 = np.load('preds_1/dMaSIF_site_1layer_15A/1A0G_B_predcoords.npy')
pred_features_1 = np.load('preds_1/dMaSIF_site_1layer_15A/1A0G_B_predfeatures_emb1.npy')

# preds_3 = 3 epoch
pred_coords_3 = np.load('preds_3/dMaSIF_site_1layer_15A/1A0G_B_predcoords.npy')
pred_features_3 = np.load('preds_3/dMaSIF_site_1layer_15A/1A0G_B_predfeatures_emb1.npy')

# preds_5 = 5 epoch
pred_coords_5 = np.load('preds_5/dMaSIF_site_1layer_15A/1A0G_B_predcoords.npy')
pred_features_5 = np.load('preds_5/dMaSIF_site_1layer_15A/1A0G_B_predfeatures_emb1.npy')

In [3]:
# these are genereated via dMaSIF

pred_coords_1.shape

(10799, 3)

In [4]:
# point cloud coords stay the same

pred_coords_1[0], pred_coords_3[0], pred_coords_5[0]

(array([-24.535849,  11.999021,   8.626174], dtype=float32),
 array([-24.535849,  11.999021,   8.626174], dtype=float32),
 array([-24.535849,  11.999021,   8.626174], dtype=float32))

In [5]:
for idx, (epoch_1, epoch_3, epoch_5) in enumerate(zip(pred_features_1[1], pred_features_3[1], pred_features_5[1])):
    print(f'{idx:10d}{epoch_1:10.3f}{epoch_3:10.3f}{epoch_5:10.3f}')

         0     0.746     0.746     0.746
         1     0.136     0.136     0.136
         2     0.447     0.447     0.447
         3     0.047     0.047     0.047
         4     0.229     0.229     0.229
         5     0.012     0.012     0.012
         6     0.113     0.113     0.113
         7     0.003     0.003     0.003
         8     0.093     0.093     0.093
         9     0.002     0.002     0.002
        10     2.666     2.911     3.087
        11     3.215     2.918     1.986
        12     0.549     0.565     1.295
        13     2.806     3.298     2.984
        14     0.384     0.466     1.489
        15     3.274     2.764     1.877
        16    -0.192     0.289    -0.376
        17     2.284     2.468     1.899
        18     1.737     1.233     1.272
        19     2.075     2.291     1.888
        20    -3.900    -4.444    -3.962
        21     0.934     0.640     1.084
        22     0.052     0.157    -0.162
        23     0.222     0.406     0.858
        24     0

### Observation#1: chemfeats evolve during training!

### Observation#2: How do reconcile the precomputed data with the point cloud data?

In [13]:
# feats_1A0G_A = np.load('surface_data/raw/01-benchmark_surfaces_npy/1A0G_A_features.npy')
atomxyz_1A0G_B = np.load('surface_data/raw/01-benchmark_surfaces_npy/1A0G_B_atomxyz.npy')
xyz_1A0G_B = np.load('surface_data/raw/01-benchmark_surfaces_npy/1A0G_B_xyz.npy')
feats_1A0G_B = np.load('surface_data/raw/01-benchmark_surfaces_npy/1A0G_B_features.npy')

In [14]:
atomxyz_1A0G_B.shape

(4564, 3)

In [15]:
# these look like the pre-computed vertices! How is this any different from _meshpoints.npy

xyz_1A0G_B.shape

(5852, 3)

In [16]:
feats_1A0G_B.shape

(5852, 3)